// Fabric and banig patterns; generated by scripts/index_fabrics.py from tela/ and banig/.
// repeat is the size of one repeat of the pattern in the room, in metres.
export const FABRICS=[
 {
  "id": "tela_155200",
  "file": "2d/fabric/tela/tela_155200.png",
  "kind": "tela",
  "group": "tela",
  "repeat": 0.6
 },
 {
  "id": "tela_170406",
  "file": "2d/fabric/tela/tela_170406.png",
  "kind": "tela",
  "group": "tela",
  "repeat": 0.6
 },
 {
  "id": "tela_170635",
  "file": "2d/fabric/tela/tela_170635.png",
  "kind": "tela",
  "group": "tela",
  "repeat": 0.6
 },
 {
  "id": "cabana_pinstripe_deped_kelly_green",
  "file": "2d/fabric/tela/cabana_pinstripe_deped_kelly_green.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "cabana_pinstripe_fiesta_crimson_red",
  "file": "2d/fabric/tela/cabana_pinstripe_fiesta_crimson_red.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "cabana_pinstripe_foam_green_classic",
  "file": "2d/fabric/tela/cabana_pinstripe_foam_green_classic.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "cabana_pinstripe_manila_maroon",
  "file": "2d/fabric/tela/cabana_pinstripe_manila_maroon.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "cabana_pinstripe_pacific_royal_blue",
  "file": "2d/fabric/tela/cabana_pinstripe_pacific_royal_blue.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "cabana_pinstripe_sunflower_yellow",
  "file": "2d/fabric/tela/cabana_pinstripe_sunflower_yellow.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "cabana_pinstripe_terracotta_orange",
  "file": "2d/fabric/tela/cabana_pinstripe_terracotta_orange.png",
  "kind": "tela",
  "group": "cabana_pinstripes",
  "repeat": 0.45
 },
 {
  "id": "floral_blue_forget_me_not_on_cream",
  "file": "2d/fabric/tela/floral_blue_forget_me_not_on_cream.png",
  "kind": "tela",
  "group": "ditsy_floral",
  "repeat": 0.45
 },
 {
  "id": "floral_retro_orange_daisy_on_mint",
  "file": "2d/fabric/tela/floral_retro_orange_daisy_on_mint.png",
  "kind": "tela",
  "group": "ditsy_floral",
  "repeat": 0.45
 },
 {
  "id": "floral_sampaguita_on_foam_green",
  "file": "2d/fabric/tela/floral_sampaguita_on_foam_green.png",
  "kind": "tela",
  "group": "ditsy_floral",
  "repeat": 0.45
 },
 {
  "id": "floral_vintage_pink_blossom_on_ecru",
  "file": "2d/fabric/tela/floral_vintage_pink_blossom_on_ecru.png",
  "kind": "tela",
  "group": "ditsy_floral",
  "repeat": 0.45
 },
 {
  "id": "fruits_fruits_155150",
  "file": "2d/fabric/tela/fruits_fruits_155150.png",
  "kind": "tela",
  "group": "fruits",
  "repeat": 0.6
 },
 {
  "id": "fruits_fruits_155154",
  "file": "2d/fabric/tela/fruits_fruits_155154.png",
  "kind": "tela",
  "group": "fruits",
  "repeat": 0.6
 },
 {
  "id": "fruits_fruits_170433",
  "file": "2d/fabric/tela/fruits_fruits_170433.png",
  "kind": "tela",
  "group": "fruits",
  "repeat": 0.6
 },
 {
  "id": "gingham_breeze_sky_blue_32px",
  "file": "2d/fabric/tela/gingham_breeze_sky_blue_32px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_carinderia_red_48px",
  "file": "2d/fabric/tela/gingham_carinderia_red_48px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_deped_foam_green_32px",
  "file": "2d/fabric/tela/gingham_deped_foam_green_32px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_monochrome_black_32px",
  "file": "2d/fabric/tela/gingham_monochrome_black_32px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_palmyra_dark_green_48px",
  "file": "2d/fabric/tela/gingham_palmyra_dark_green_48px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_school_navy_48px",
  "file": "2d/fabric/tela/gingham_school_navy_48px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_sunshine_yellow_32px",
  "file": "2d/fabric/tela/gingham_sunshine_yellow_32px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_vintage_rose_32px",
  "file": "2d/fabric/tela/gingham_vintage_rose_32px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "gingham_warm_terracotta_48px",
  "file": "2d/fabric/tela/gingham_warm_terracotta_48px.png",
  "kind": "tela",
  "group": "gingham",
  "repeat": 0.32
 },
 {
  "id": "graphic_graphic_173307",
  "file": "2d/fabric/tela/graphic_graphic_173307.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173310",
  "file": "2d/fabric/tela/graphic_graphic_173310.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173321",
  "file": "2d/fabric/tela/graphic_graphic_173321.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173330",
  "file": "2d/fabric/tela/graphic_graphic_173330.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173400",
  "file": "2d/fabric/tela/graphic_graphic_173400.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173524",
  "file": "2d/fabric/tela/graphic_graphic_173524.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173643",
  "file": "2d/fabric/tela/graphic_graphic_173643.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173705",
  "file": "2d/fabric/tela/graphic_graphic_173705.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173729",
  "file": "2d/fabric/tela/graphic_graphic_173729.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_173900",
  "file": "2d/fabric/tela/graphic_graphic_173900.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_174012",
  "file": "2d/fabric/tela/graphic_graphic_174012.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_174041",
  "file": "2d/fabric/tela/graphic_graphic_174041.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_175130",
  "file": "2d/fabric/tela/graphic_graphic_175130.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_175321",
  "file": "2d/fabric/tela/graphic_graphic_175321.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "graphic_graphic_175457",
  "file": "2d/fabric/tela/graphic_graphic_175457.png",
  "kind": "tela",
  "group": "graphic",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_165805",
  "file": "2d/fabric/tela/kids_kids_165805.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_165811",
  "file": "2d/fabric/tela/kids_kids_165811.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_165816",
  "file": "2d/fabric/tela/kids_kids_165816.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170142",
  "file": "2d/fabric/tela/kids_kids_170142.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170145",
  "file": "2d/fabric/tela/kids_kids_170145.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170148",
  "file": "2d/fabric/tela/kids_kids_170148.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170220",
  "file": "2d/fabric/tela/kids_kids_170220.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170417",
  "file": "2d/fabric/tela/kids_kids_170417.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170420",
  "file": "2d/fabric/tela/kids_kids_170420.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170755",
  "file": "2d/fabric/tela/kids_kids_170755.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170757",
  "file": "2d/fabric/tela/kids_kids_170757.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170800",
  "file": "2d/fabric/tela/kids_kids_170800.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kids_kids_170837",
  "file": "2d/fabric/tela/kids_kids_170837.png",
  "kind": "tela",
  "group": "kids",
  "repeat": 0.6
 },
 {
  "id": "kurtina_slub_calamansi_citrus",
  "file": "2d/fabric/tela/kurtina_slub_calamansi_citrus.png",
  "kind": "tela",
  "group": "kurtina_slub_stripes",
  "repeat": 0.45
 },
 {
  "id": "kurtina_slub_deped_foam_harvest",
  "file": "2d/fabric/tela/kurtina_slub_deped_foam_harvest.png",
  "kind": "tela",
  "group": "kurtina_slub_stripes",
  "repeat": 0.45
 },
 {
  "id": "kurtina_slub_manila_bay_blue_gold",
  "file": "2d/fabric/tela/kurtina_slub_manila_bay_blue_gold.png",
  "kind": "tela",
  "group": "kurtina_slub_stripes",
  "repeat": 0.45
 },
 {
  "id": "kurtina_slub_palmyra_olive_yellow",
  "file": "2d/fabric/tela/kurtina_slub_palmyra_olive_yellow.png",
  "kind": "tela",
  "group": "kurtina_slub_stripes",
  "repeat": 0.45
 },
 {
  "id": "kurtina_slub_sampaguita_rose_gold",
  "file": "2d/fabric/tela/kurtina_slub_sampaguita_rose_gold.png",
  "kind": "tela",
  "group": "kurtina_slub_stripes",
  "repeat": 0.45
 },
 {
  "id": "kurtina_slub_sunflower_amber_brown",
  "file": "2d/fabric/tela/kurtina_slub_sunflower_amber_brown.png",
  "kind": "tela",
  "group": "kurtina_slub_stripes",
  "repeat": 0.45
 },
 {
  "id": "plaid_deped_green_harvest",
  "file": "2d/fabric/tela/plaid_deped_green_harvest.png",
  "kind": "tela",
  "group": "plaid_madras",
  "repeat": 0.5
 },
 {
  "id": "plaid_ilocano_red_gold_navy",
  "file": "2d/fabric/tela/plaid_ilocano_red_gold_navy.png",
  "kind": "tela",
  "group": "plaid_madras",
  "repeat": 0.5
 },
 {
  "id": "plaid_inabel_fiesta_check",
  "file": "2d/fabric/tela/plaid_inabel_fiesta_check.png",
  "kind": "tela",
  "group": "plaid_madras",
  "repeat": 0.5
 },
 {
  "id": "plaid_rustic_earth_flannel",
  "file": "2d/fabric/tela/plaid_rustic_earth_flannel.png",
  "kind": "tela",
  "group": "plaid_madras",
  "repeat": 0.5
 },
 {
  "id": "plaid_vintage_pastel_blanket",
  "file": "2d/fabric/tela/plaid_vintage_pastel_blanket.png",
  "kind": "tela",
  "group": "plaid_madras",
  "repeat": 0.5
 },
 {
  "id": "polka_carnival_red_on_cream_classic_aligned",
  "file": "2d/fabric/tela/polka_carnival_red_on_cream_classic_aligned.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "polka_dusty_rose_on_ecru_classic_staggered",
  "file": "2d/fabric/tela/polka_dusty_rose_on_ecru_classic_staggered.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "polka_foam_green_on_cream_coin_staggered",
  "file": "2d/fabric/tela/polka_foam_green_on_cream_coin_staggered.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "polka_navy_on_crisp_white_coin_staggered",
  "file": "2d/fabric/tela/polka_navy_on_crisp_white_coin_staggered.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "polka_sunshine_on_sky_blue_pindot_staggered",
  "file": "2d/fabric/tela/polka_sunshine_on_sky_blue_pindot_staggered.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "polka_white_on_foam_green_classic_staggered",
  "file": "2d/fabric/tela/polka_white_on_foam_green_classic_staggered.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "polka_white_on_palmyra_green_pindot_staggered",
  "file": "2d/fabric/tela/polka_white_on_palmyra_green_pindot_staggered.png",
  "kind": "tela",
  "group": "polka_dots",
  "repeat": 0.4
 },
 {
  "id": "wave_foam_green_waves",
  "file": "2d/fabric/tela/wave_foam_green_waves.png",
  "kind": "tela",
  "group": "retro_waves",
  "repeat": 0.45
 },
 {
  "id": "wave_ocean_gold_waves",
  "file": "2d/fabric/tela/wave_ocean_gold_waves.png",
  "kind": "tela",
  "group": "retro_waves",
  "repeat": 0.45
 },
 {
  "id": "wave_sunset_rose_waves",
  "file": "2d/fabric/tela/wave_sunset_rose_waves.png",
  "kind": "tela",
  "group": "retro_waves",
  "repeat": 0.45
 },
 {
  "id": "sparrow333_sparrow333_154342",
  "file": "2d/fabric/tela/sparrow333_sparrow333_154342.png",
  "kind": "tela",
  "group": "sparrow333",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_sparrow333_154355",
  "file": "2d/fabric/tela/sparrow333_sparrow333_154355.png",
  "kind": "tela",
  "group": "sparrow333",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_sparrow333_154416",
  "file": "2d/fabric/tela/sparrow333_sparrow333_154416.png",
  "kind": "tela",
  "group": "sparrow333",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_sparrow333_154426",
  "file": "2d/fabric/tela/sparrow333_sparrow333_154426.png",
  "kind": "tela",
  "group": "sparrow333",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_sparrow333_154438",
  "file": "2d/fabric/tela/sparrow333_sparrow333_154438.png",
  "kind": "tela",
  "group": "sparrow333",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_152521",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_152521.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_152525",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_152525.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_152528",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_152528.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_152531",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_152531.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_153809",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_153809.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_153812",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_153812.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_153816",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_153816.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_153819",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_153819.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_154022",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_154022.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_154025",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_154025.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_154028",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_154028.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "sparrow333_flowerdominant_flowerdominant_154031",
  "file": "2d/fabric/tela/sparrow333_flowerdominant_flowerdominant_154031.png",
  "kind": "tela",
  "group": "flowerdominant",
  "repeat": 0.6
 },
 {
  "id": "ticking_charcoal_on_ecru",
  "file": "2d/fabric/tela/ticking_charcoal_on_ecru.png",
  "kind": "tela",
  "group": "ticking_stripes",
  "repeat": 0.3
 },
 {
  "id": "ticking_navy_on_linen",
  "file": "2d/fabric/tela/ticking_navy_on_linen.png",
  "kind": "tela",
  "group": "ticking_stripes",
  "repeat": 0.3
 },
 {
  "id": "ticking_palmyra_on_foam",
  "file": "2d/fabric/tela/ticking_palmyra_on_foam.png",
  "kind": "tela",
  "group": "ticking_stripes",
  "repeat": 0.3
 },
 {
  "id": "ticking_red_on_cream",
  "file": "2d/fabric/tela/ticking_red_on_cream.png",
  "kind": "tela",
  "group": "ticking_stripes",
  "repeat": 0.3
 },
 {
  "id": "banig_170002",
  "file": "2d/fabric/banig/banig_170002.png",
  "kind": "banig",
  "group": "banig",
  "repeat": 0.5
 },
 {
  "id": "banig_geometric_tikog_antique_unbleached_rush",
  "file": "2d/fabric/banig/banig_geometric_tikog_antique_unbleached_rush.png",
  "kind": "banig",
  "group": "geometric_tikog",
  "repeat": 0.5
 },
 {
  "id": "banig_geometric_tikog_ilocos_inabel_earth",
  "file": "2d/fabric/banig/banig_geometric_tikog_ilocos_inabel_earth.png",
  "kind": "banig",
  "group": "geometric_tikog",
  "repeat": 0.5
 },
 {
  "id": "banig_geometric_tikog_samar_madder_ochre",
  "file": "2d/fabric/banig/banig_geometric_tikog_samar_madder_ochre.png",
  "kind": "banig",
  "group": "geometric_tikog",
  "repeat": 0.5
 },
 {
  "id": "banig_geometric_tikog_sulu_mangosteen_emerald",
  "file": "2d/fabric/banig/banig_geometric_tikog_sulu_mangosteen_emerald.png",
  "kind": "banig",
  "group": "geometric_tikog",
  "repeat": 0.5
 },
 {
  "id": "banig_neon_neon_cyan_lagoon",
  "file": "2d/fabric/banig/banig_neon_neon_cyan_lagoon.png",
  "kind": "banig",
  "group": "neon_plastic",
  "repeat": 0.5
 },
 {
  "id": "banig_neon_neon_emerald_chartreuse",
  "file": "2d/fabric/banig/banig_neon_neon_emerald_chartreuse.png",
  "kind": "banig",
  "group": "neon_plastic",
  "repeat": 0.5
 },
 {
  "id": "banig_neon_neon_fiesta_purple",
  "file": "2d/fabric/banig/banig_neon_neon_fiesta_purple.png",
  "kind": "banig",
  "group": "neon_plastic",
  "repeat": 0.5
 },
 {
  "id": "banig_neon_neon_royal_hot_pink",
  "file": "2d/fabric/banig/banig_neon_neon_royal_hot_pink.png",
  "kind": "banig",
  "group": "neon_plastic",
  "repeat": 0.5
 },
 {
  "id": "banig_neon_neon_sunburst_tangerine",
  "file": "2d/fabric/banig/banig_neon_neon_sunburst_tangerine.png",
  "kind": "banig",
  "group": "neon_plastic",
  "repeat": 0.5
 },
 {
  "id": "banig_pastel_coastal_bleached_blue",
  "file": "2d/fabric/banig/banig_pastel_coastal_bleached_blue.png",
  "kind": "banig",
  "group": "pastel_faded",
  "repeat": 0.5
 },
 {
  "id": "banig_pastel_faded_lavender_sage",
  "file": "2d/fabric/banig/banig_pastel_faded_lavender_sage.png",
  "kind": "banig",
  "group": "pastel_faded",
  "repeat": 0.5
 },
 {
  "id": "banig_pastel_pastel_foamgreen_peach",
  "file": "2d/fabric/banig/banig_pastel_pastel_foamgreen_peach.png",
  "kind": "banig",
  "group": "pastel_faded",
  "repeat": 0.5
 },
 {
  "id": "banig_pastel_pastel_rose_periwinkle",
  "file": "2d/fabric/banig/banig_pastel_pastel_rose_periwinkle.png",
  "kind": "banig",
  "group": "pastel_faded",
  "repeat": 0.5
 },
 {
  "id": "banig_pastel_sunfaded_retro_mint",
  "file": "2d/fabric/banig/banig_pastel_sunfaded_retro_mint.png",
  "kind": "banig",
  "group": "pastel_faded",
  "repeat": 0.5
 },
 {
  "id": "banig_traditional_antique_unbleached_rush",
  "file": "2d/fabric/banig/banig_traditional_antique_unbleached_rush.png",
  "kind": "banig",
  "group": "traditional_natural",
  "repeat": 0.5
 },
 {
  "id": "banig_traditional_ilocos_inabel_earth",
  "file": "2d/fabric/banig/banig_traditional_ilocos_inabel_earth.png",
  "kind": "banig",
  "group": "traditional_natural",
  "repeat": 0.5
 },
 {
  "id": "banig_traditional_samar_madder_ochre",
  "file": "2d/fabric/banig/banig_traditional_samar_madder_ochre.png",
  "kind": "banig",
  "group": "traditional_natural",
  "repeat": 0.5
 },
 {
  "id": "banig_traditional_sulu_mangosteen_emerald",
  "file": "2d/fabric/banig/banig_traditional_sulu_mangosteen_emerald.png",
  "kind": "banig",
  "group": "traditional_natural",
  "repeat": 0.5
 }
];
