// Generated by scripts/index_wall_assets.py; paths are project-relative.
export const WALL_HANGINGS = [
  {
    "file": "2d/wall hanging/photos/band_agadiers_coarse_420.png",
    "aspect": 0.7545008183306056
  },
  {
    "file": "2d/wall hanging/photos/Calendar.png",
    "aspect": 1.309608540925267
  },
  {
    "file": "2d/wall hanging/photos/family_gathering_coarse_800.png",
    "aspect": 0.9391534391534392
  },
  {
    "file": "2d/wall hanging/photos/family_lowpoly_coarse_1200.png",
    "aspect": 0.67109375
  },
  {
    "file": "2d/wall hanging/photos/family_portrait_studio_coarse_850.png",
    "aspect": 1.3871866295264623
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_01_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_02_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_03_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_04_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_05_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_06_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_07_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/familyphoto_08_coarse.png",
    "aspect": 1.248888888888889
  },
  {
    "file": "2d/wall hanging/photos/medals.png",
    "aspect": 0.7169117647058824
  },
  {
    "file": "2d/wall hanging/photos/wedding_portrait_coarse_750.png",
    "aspect": 1.675233644859813
  }
];
export const CURTAIN_TEXTURES = [
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-07-29.png",
    "aspect": 1.3392857142857142
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-07-38.png",
    "aspect": 0.8975903614457831
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-07-58.png",
    "aspect": 0.47696476964769646
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-08-12.png",
    "aspect": 0.33884297520661155
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-08-19.png",
    "aspect": 1.8724489795918366
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-09-45.png",
    "aspect": 1.1981707317073171
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-27-53.png",
    "aspect": 1.2124183006535947
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-28-04.png",
    "aspect": 0.8775981524249422
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-28-25.png",
    "aspect": 1.1925133689839573
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-28-35.png",
    "aspect": 1.1861702127659575
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-28-41.png",
    "aspect": 1.3715170278637772
  },
  {
    "file": "2d/wall hanging/kurtina/2026-10-03 17-28-47.png",
    "aspect": 1.2612359550561798
  }
];
