"""Rebuild the floor tile bank: python scripts/index_floor_tiles.py

Lists the images in `2d/floor tiles/` into `floor-tiles.js`. The width of floor an image
covers is read from its name, as centimetres before the extension: `marble_60cm.png`.
A name with no size is taken as 40 cm. Image size is read from the file.
"""
from pathlib import Path
import argparse
import json
import re
import sys


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    try:
        from PIL import Image
    except ImportError:
        print('Pillow is needed to read image sizes: pip install pillow')
        return 1
    entries, unsized = [], []
    folder = args.root / '2d' / 'floor tiles'
    for path in sorted(folder.iterdir()):
        if path.suffix.lower() not in ('.png', '.jpg', '.jpeg', '.webp'):
            continue
        with Image.open(path) as image:
            width, height = image.size
        match = re.search(r'(\d+)\s*cm$', path.stem, flags=re.I)
        if not match:
            unsized.append(path.name)
        entries.append(dict(file='2d/floor tiles/' + path.name, metres=(int(match.group(1)) if match else 40) / 100, aspect=height / width))
    target = args.root / 'floor-tiles.js'
    target.write_text('// Floor tile bank; generated by scripts/index_floor_tiles.py from 2d/floor tiles/.\nexport const FLOOR_TILE_IMAGES=' + json.dumps(entries, indent=2) + ';\n', encoding='utf-8')
    print(f'Indexed {len(entries)} floor images.')
    if unsized:
        print('No size in the name, 40 cm assumed:', ', '.join(unsized))
    return 0


if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.exit(main())
