"""Rebuild cutout metadata after renames: python scripts/index_raw_objects.py.

Reads PNG dimensions without changing supplied images. Wall electrical cutouts
are excluded until the renderer supports wall mounting.
"""
from pathlib import Path
import argparse
import json
import struct

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    aliases = dict(zip(['sunny_pitcher_pink','sunny_pitcher_turquoise','orocan_drawer_chest','orocan_icebox_15l','stockpot_stainless','cooking_pot_black_handles','cooking_pot_wire_handles','intermediate_pad','intermediate_pad_cover','frying_pan_stainless','yellowpad'], ['rawPitcherPink','rawPitcherBlue','rawDrawers','rawCooler','rawPotSilver','rawPotGlass','rawPotLid','rawIntermediatePad','rawPadCover','rawFryingPan','rawYellowPad']))
    entries = []
    for path in sorted((args.root / '2d/raw objects').glob('*.png')):
        name = path.stem
        if name in ('wall_outlet_duplex_white','receptacle_box_surface'):
            continue
        data = path.read_bytes()
        if data[:8] != b'\x89PNG\r\n\x1a\n':
            raise ValueError(f'Not a PNG: {path}')
        width, height = struct.unpack('>II', data[16:24])
        aspect = height / width
        floor = name.startswith(('orocan','batya','backpack','teddy','hydrangea','sunflower','surf_jug','zonrox'))
        flat = name in ('yellowpad','intermediate_pad','intermediate_pad_cover','envelope_kraft','jeans_blue','tshirt_red','athletic_shorts_black')
        mode = 'floor' if floor else 'flat' if flat else 'table'
        rooms = ['sala','bedroom'] if flat or name.startswith(('teddy','backpack')) else ['sala','kitchen']
        if name.startswith(('surf','zonrox','batya')):
            rooms = ['bathroom','kitchen','bare']
        if name.startswith('orocan'):
            rooms = ['sala','bedroom','kitchen','bare']
        size = (0.65 if 'drawer' in name else 0.4) if floor else min(0.3, 0.43/aspect)
        entries.append(dict(id=aliases.get(name,'raw'+''.join(part.title() for part in name.split('_'))),file='2d/raw objects/'+path.name,aspect=aspect,width=size,mode=mode,rooms=rooms))
    target = args.root / 'raw-object-assets.js'
    source = target.read_text(encoding='utf-8')
    renderer = source[source.index('export function createRawObject'):]
    target.write_text('// User-supplied cutouts; generated by scripts/index_raw_objects.py.\nexport const RAW_OBJECTS='+json.dumps(entries, indent=2)+';\n\n'+renderer, encoding='utf-8')
    print(f'Indexed {len(entries)} cutouts; two electrical wall cutouts deferred.')

if __name__ == '__main__':
    main()
