"""Index supplied wall photos and curtain textures for the static browser scene.

Usage: python scripts/index_wall_assets.py [--contact-sheet asset-sheet.jpg]
Requires Pillow. Run again after adding images to the two source folders.
"""
import argparse
import json
import sys
from pathlib import Path
from PIL import Image, ImageDraw

def main():
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--project', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--contact-sheet', type=Path)
    args = parser.parse_args()
    groups = {}
    paths = []
    for name, folder in [('WALL_HANGINGS', 'photos'), ('CURTAIN_TEXTURES', 'kurtina')]:
        entries = []
        for path in sorted((args.project / '2d' / 'wall hanging' / folder).glob('*.png')):
            with Image.open(path) as img:
                w, h = img.size
                entries.append({'file': path.relative_to(args.project).as_posix(), 'aspect': h / w})
            paths.append(path)
        groups[name] = entries
    content = '// Generated by scripts/index_wall_assets.py; paths are project-relative.\n'
    for name, entries in groups.items():
        content += f'export const {name} = {json.dumps(entries, ensure_ascii=False, indent=2)};\n'
    (args.project / 'wall-assets.js').write_text(content, encoding='utf-8')
    if args.contact_sheet:
        sheet = Image.new('RGB', (1000, ((len(paths) + 3) // 4) * 210), '#eeeeee')
        draw = ImageDraw.Draw(sheet)
        for i, path in enumerate(paths):
            with Image.open(path) as img:
                img = img.convert('RGBA')
                img.thumbnail((235, 175))
                x, y = (i % 4) * 250, (i // 4) * 210
                sheet.paste(img, (x, y), img)
                draw.text((x + 4, y + 178), path.stem[:31], fill='black')
        sheet.save(args.contact_sheet)
    print(', '.join(f'{len(items)} {name}' for name, items in groups.items()))

if __name__ == '__main__':
    main()
